import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

export const metadata = {
  title: "Welcome to Dashbaord",
  description: "Generated by create next app",
 
};



// app/(dashboard)/layout.js
export default function DashboardLayout({ children }) {
    return (
      <div  className="relative "  >
          <div className="">  
          <  Navbar/>


          </div>
       
       <div  className="flex  "> <Sidebar/>
        
        <section className="flex min-h-screen flex-1 flex-col px-6 pb-6 
        pt-28 max-md:pb-14 sm:px-14  ">

        <div className="w-full ">{children}   </div>

    
          </section>    
      


          </div>
        


      </div>
    );
  }